### ISSUE TITLE
The application is in brake mode

### ISSUE THREAD

**Issue by AyubAutomation** [narchibald/dotnet-ewelink-api#3]
after exciting the following line 
 await link.SetDevicePowerState("10004d359a", "toggle", 1);
the application breaks and displays following!
![error](https://user-images.githubusercontent.com/101476783/163251054-00436bab-7460-46f9-85fd-37d7c4f388e4.JPG)

**Comment by narchibald** [comment]
Was there a stack track with the exception?
If not what kind of device are you using? I might be able to replicate the problem if I have a similar device.

**Comment by AyubAutomation** [comment]
No there was not, I am using "sonoff basic"
![sonoff basic](https://user-images.githubusercontent.com/101476783/163325218-5414c7cd-0058-4db4-b47c-e440756c877a.jpg)

**Comment by narchibald** [comment]
Awesome I have one of those. I will give it a test and hopefully replicate the issue.

**Comment by AyubAutomation** [comment]
Hello, I tested Sonoff mini device still same issue!

**Comment by narchibald** [comment]
Thanks for reporting the bug. I have now fixed it. There was an issue loading the embedded JSON files from the assembly.
